//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolrDeployCmdlets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolrDeployCmdlets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr Master Worker Role {0} has been created at &apos;{1}&apos; with instance count {2}. By default only local storage is set in the configuration. Please make sure to call Set-AzureSolrStorageAccount command to set Windows Azure Storage account before publishing your service to Windows Azure..
        /// </summary>
        internal static string AddAzureSolrMasterWorkerRoleSuccessMessage {
            get {
                return ResourceManager.GetString("AddAzureSolrMasterWorkerRoleSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr Slave Worker Role {0} has been created at &apos;{1}&apos; with instance count {2}. By default only local storage is set in the configuration. Please make sure to call Set-AzureSolrStorageAccount command to set Windows Azure Storage account before publishing your service to Windows Azure..
        /// </summary>
        internal static string AddAzureSolrSlaveWorkerRoleSuccessMessage {
            get {
                return ResourceManager.GetString("AddAzureSolrSlaveWorkerRoleSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr Web Role {0} has been created at &apos;{1}&apos;. By default only local storage is set in the configuration. Please make sure to call Set-AzureSolrStorageAccount command to set Windows Azure Storage account before publishing your service to Windows Azure..
        /// </summary>
        internal static string AddAzureSolrWebRoleSuccessMessage {
            get {
                return ResourceManager.GetString("AddAzureSolrWebRoleSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Azure SDK/v1.6/bin.
        /// </summary>
        internal static string AzureSdkBinFolder {
            get {
                return ResourceManager.GetString("AzureSdkBinFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Azure SDK Deployment Cmdlets.
        /// </summary>
        internal static string AzureSdkDirectoryName {
            get {
                return ResourceManager.GetString("AzureSdkDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find {0} directory. Please run Import-AzureService -Path cmdlet to create {0} directory..
        /// </summary>
        internal static string AzureSdkDirectoryNotFound {
            get {
                return ResourceManager.GetString("AzureSdkDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; already exists..
        /// </summary>
        internal static string AzureStorageAccountAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("AzureStorageAccountAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure storage account configured..
        /// </summary>
        internal static string AzureStorageAccountConfiguredForSolrRoleMessage {
            get {
                return ResourceManager.GetString("AzureStorageAccountConfiguredForSolrRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; created..
        /// </summary>
        internal static string AzureStorageAccountCreatedMessage {
            get {
                return ResourceManager.GetString("AzureStorageAccountCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate was found in the certificate store with thumbprint {0}..
        /// </summary>
        internal static string CertificateNotFoundInStore {
            get {
                return ResourceManager.GetString("CertificateNotFoundInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating storage service {0}.
        /// </summary>
        internal static string CreateStorageAccountWaitMessage {
            get {
                return ResourceManager.GetString("CreateStorageAccountWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataConnectionString.
        /// </summary>
        internal static string DataConnectionString {
            get {
                return ResourceManager.GetString("DataConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString.
        /// </summary>
        internal static string DiagnosticsConnectionString {
            get {
                return ResourceManager.GetString("DiagnosticsConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate format. Publish settings may be corrupted. Use Get-AzurePublishSettings to download updated settings..
        /// </summary>
        internal static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist in {1} or you&apos;ve not passed valid value for it..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided publish settings file {0} has invalid content. Please get valid by running cmdlet Get-AzurePublishSettings..
        /// </summary>
        internal static string InvalidPublishSettingsSchema {
            get {
                return ResourceManager.GetString("InvalidPublishSettingsSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolrMasterEndpoint.
        /// </summary>
        internal static string MasterWorkerRoleInputEndpointName {
            get {
                return ResourceManager.GetString("MasterWorkerRoleInputEndpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolrMasterHostWorkerRole.
        /// </summary>
        internal static string MasterWorkerRoleName {
            get {
                return ResourceManager.GetString("MasterWorkerRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .PublishSettings.
        /// </summary>
        internal static string PublishSettingsFileExtention {
            get {
                return ResourceManager.GetString("PublishSettingsFileExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.PublishSettings.
        /// </summary>
        internal static string PublishSettingsFileName {
            get {
                return ResourceManager.GetString("PublishSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConfiguration.Cloud.cscfg.
        /// </summary>
        internal static string ServiceConfigurationCloudFileName {
            get {
                return ResourceManager.GetString("ServiceConfigurationCloudFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConfiguration.Local.cscfg.
        /// </summary>
        internal static string ServiceConfigurationLocalFileName {
            get {
                return ResourceManager.GetString("ServiceConfigurationLocalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDefinition.csdef.
        /// </summary>
        internal static string ServiceDefinitionFileName {
            get {
                return ResourceManager.GetString("ServiceDefinitionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deploymentSettings.json.
        /// </summary>
        internal static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolrSlaveEndpoint.
        /// </summary>
        internal static string SlaveWorkerRoleInputEndpointName {
            get {
                return ResourceManager.GetString("SlaveWorkerRoleInputEndpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolrSlaveHostWorkerRole.
        /// </summary>
        internal static string SlaveWorkerRoleName {
            get {
                return ResourceManager.GetString("SlaveWorkerRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr\SolrMasterHostWorkerRole.
        /// </summary>
        internal static string SolrMasterWorkerRoleScaffoldFolder {
            get {
                return ResourceManager.GetString("SolrMasterWorkerRoleScaffoldFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallLocation.
        /// </summary>
        internal static string SolrOnAzureSDKInstallLocationKey {
            get {
                return ResourceManager.GetString("SolrOnAzureSDKInstallLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\SolrOnAzure\SolrInstWR.
        /// </summary>
        internal static string SolrOnAzureSDKRegistrySectionName {
            get {
                return ResourceManager.GetString("SolrOnAzureSDKRegistrySectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr\SolrSlaveHostWorkerRole.
        /// </summary>
        internal static string SolrSlaveWorkerRoleScaffoldFolder {
            get {
                return ResourceManager.GetString("SolrSlaveWorkerRoleScaffoldFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr\SolrAdminWebRole.
        /// </summary>
        internal static string SolrWebRoleScaffoldFolder {
            get {
                return ResourceManager.GetString("SolrWebRoleScaffoldFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided subscription name doesn&apos;t exist in the imported publish profile. If subscriptions have changed for the hosted service, retrieve an updated profile by using Get-AzurePublishSettings then import the profile using Import-AzurePublishSettings..
        /// </summary>
        internal static string SubscriptionIdNotFoundMessage {
            get {
                return ResourceManager.GetString("SubscriptionIdNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr Master Worker Role {0} already exists. Instance count updated to {1}..
        /// </summary>
        internal static string UpdateAzureSolrMasterWorkerRoleSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateAzureSolrMasterWorkerRoleSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr Web Role {0} already exists. Instance count updated to {1}..
        /// </summary>
        internal static string UpdateAzureSolrWebRoleSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateAzureSolrWebRoleSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolrAdminWebRole.
        /// </summary>
        internal static string WebRoleName {
            get {
                return ResourceManager.GetString("WebRoleName", resourceCulture);
            }
        }
    }
}
